# Generated by Django 4.2.4 on 2023-10-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='branch',
            new_name='branch1',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='domain',
            new_name='domain1',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='mode',
            new_name='mode1',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='year',
            new_name='year1',
        ),
        migrations.RemoveField(
            model_name='empmodel',
            name='mail',
        ),
    ]
