# Generated by Django 4.2.4 on 2023-10-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_branch_empmodel_branch1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='branch1',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='domain1',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='mode1',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='empmodel',
            old_name='year1',
            new_name='year',
        ),
    ]
